---
version: 2
project_name: fzf

before:
  hooks:
    - go mod download

builds:
  - id: fzf
    goos:
      - linux
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
      - loong64
      - ppc64le
      - s390x
    goarm:
      - 5
      - 6
      - 7
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.revision={{ .ShortCommit }}"
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: openbsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: openbsd
        goarch: arm64

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - fzf
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - non-existent*

release:
  github:
    owner: junegunn
    name: fzf
  prerelease: auto
  name_template: '{{ .Version }}'

snapshot:
  name_template: "{{ .Version }}-devel"

changelog:
  sort: asc
  filters:
    exclude:
      - README
      - test
